// src/app/components/add-book/add-book.component.ts
import { Component } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { HttpService } from '../services/http.service';
import { Book } from '../models/book';

@Component({
  selector: 'app-add-book',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './add-book.component.html',
  styleUrls: ['./add-book.component.css']
})
export class AddBookComponent {
  newBook: Book = {
    id: 0, // id is typically generated by the backend
    title: '',
    author: '',
    isbn: '',
    available: true,
    pictureUrl: ''
  };

  constructor(private httpService: HttpService) {}

  onSubmit(form: NgForm) {
    if (form.valid) {
      this.httpService.addBook(this.newBook).subscribe({
        next: (book) => {
          console.log('Book added', book);
          form.resetForm();  // Reset the form after successful submission
        },
        error: (error) => console.error('Failed to add book', error)
      });
    }
  }
}
